apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-dev
  labels:
    app: apache-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-dev
  template:
    metadata:
      labels:
        app: apache-dev
    spec:
      containers:
      - name: apache-dev
        image: httpd 
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo this is dev > /usr/local/apache2/htdocs/index.html"]
        ports:
        - containerPort: 80