apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-prod
  namespace: argocd
  labels:
    app: apache-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-prod
  template:
    metadata:
      labels:
        app: apache-prod
    spec:
      containers:
      - name: apache-prod
        image: httpd 
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo this is prod > /usr/local/apache2/htdocs/index.html"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-entrypoint
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30030