apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-prod
  labels:
    app: apache-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-prod
  template:
    metadata:
      labels:
        app: apache-prod
    spec:
      containers:
      - name: apache-prod
        image: httpd 
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo this is prod > /usr/local/apache2/htdocs/index.html"]
        ports:
        - containerPort: 80
